Prn231_FinalProject/Client/Models/Output.cs
namespace Client.Models;

public partial class Output
{
    public string Id { get; set; }

    public DateTime? DateOutput { get; set; }
}

Prn231_FinalProject/Client/Controllers/OutputController.cs
using Client.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace Client.Controllers
{
    public class OutputController : Controller
    {
        private readonly HttpClient client = null;
        private string OutApiUrl = "";
        public static List<Output> _output;
        public static List<Models.Object> _products;
        public static List<Models.Customer> _customers;
        private string ProductApiUrl = "";
        private string InputApiUrl = "";
        private string OutputApiUrl = "";
        private string CustomerAPIUrl = "";
        public OutputController()
        {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            ProductApiUrl = "https://localhost:7073/api/Product";
            InputApiUrl = "https://localhost:7073/api/Input";
            OutputApiUrl = "https://localhost:7073/api/Output";
            CustomerAPIUrl = "https://localhost:7073/api/Customer";
        }

        public async Task<IActionResult> Index()
        {
            HttpResponseMessage response = await client.GetAsync(ProductApiUrl);
            string strData = await response.Content.ReadAsStringAsync();
            var option = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            List<Models.Object> listProducts = JsonSerializer.Deserialize<List<Models.Object>>(strData, option);
            var selectListProduct = new List<SelectListItem>();
            foreach (var item in listProducts)
            {
                selectListProduct.Add(new SelectListItem { Text = "" + item.DisplayName, Value = "" + item.Id });
            }
            ViewBag.SelectListProduct = selectListProduct;

            HttpResponseMessage response2 = await client.GetAsync(CustomerAPIUrl);
            string strData2 = await response2.Content.ReadAsStringAsync();
            List<Models.Customer> listCustomers = JsonSerializer.Deserialize<List<Models.Customer>>(strData2, option);
            var selectListCustomer = new List<SelectListItem>();
            foreach (var item in listCustomers)
            {
                selectListCustomer.Add(new SelectListItem { Text = "" + item.DisplayName, Value = "" + item.Id });
            }
            ViewData["SelectListCustomer"] = selectListCustomer;


            HttpResponseMessage response3 = await client.GetAsync(OutputApiUrl);
            string strData3 = await response3.Content.ReadAsStringAsync();
            List<Models.OutputInfo> listOutputInfos = JsonSerializer.Deserialize<List<Models.OutputInfo>>(strData3, option);
            ViewData["MyList"] = listOutputInfos;

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> addOutPut()
        {
            DateTime timeOutput = DateTime.Now;
            var id = GenerateRandom();
            HttpResponseMessage response = await client.GetAsync(OutputApiUrl);
            string strData = await response.Content.ReadAsStringAsync();
            var option = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            List<Models.Output> listOutput = JsonSerializer.Deserialize<List<Models.Output>>(strData, option);
            foreach (var item in listOutput)
            {
                if (item.Id.Equals("" + id))
                {
                    id = GenerateRandom();
                }
            }
            Output o = new Output()
            {
                Id = "" + id,
                DateOutput = timeOutput,
            };

            string data = JsonSerializer.Serialize(o);
            await client.PostAsync(OutputApiUrl + "/CreateNewOutPut", new StringContent(data, Encoding.UTF8, "application/json"));
            string idObject = Request.Form["productId"];
            string quantity = Request.Form["Quantity"];
            string customerId = Request.Form["customerId"];

            HttpResponseMessage response2 = await client.GetAsync(InputApiUrl);
            string strData2 = await response2.Content.ReadAsStringAsync();
            var option2 = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };
            List<Models.InputInfo> listInfo = JsonSerializer.Deserialize<List<Models.InputInfo>>(strData2, option2);
            var count = 0;
            foreach (var item in listInfo)
            {
                if (item.IdObject.Equals(idObject))
                {
                    count += item.Count;
                }
            }
            if (Int32.Parse(quantity) > count)
            {
                return View();
            }

            OutputInfo output = new OutputInfo()
            {
                Id = "" + id,
                IdObject = idObject,
                Count = Int32.Parse(quantity),
                Status = "Success",
                IdOutput = "" + id,
                IdCustomer = Int32.Parse(customerId),
                IdInputSelct = "" + GenerateRandom(),
                IdCustomerNavigation = { },
                InputSelects = { },
                IdObjectNavigation = { },
                IdOutputNavigation = { }


            };
            string data2 = JsonSerializer.Serialize(output);
            await client.PostAsync(OutputApiUrl + "/CreateNewOutPutInfos", new StringContent(data2, Encoding.UTF8, "application/json"));


            return RedirectToAction(nameof(Index));


        }

        [HttpPost]
        public async Task<IActionResult> editOutPut(Output output)
        {
            if (ModelState.IsValid)
            {
                string data = JsonSerializer.Serialize(output);
                await client.PostAsync(OutApiUrl, new StringContent(data, Encoding.UTF8, "application/json"));
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public int GenerateRandom()
        {
            Random random = new Random();
            return random.Next(10000, 100000); // Generates a random number between 10000 and 99999

        }
    }
}

Prn231_FinalProject/Client/Views/Output/Index.cshtml
@using API.Models;
@*
*@
@{
    var myList = ViewData["MyList"] as List<OutputInfo>;
}
<div class="content-wrapper" style="background-color:#bddcff;">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="d-flex justify-content-between align-items-center">
                <div>
                    <a href="#" data-toggle="tooltip" title="Add ">
                        <button type="button" class="btn btn-primary btn-icon-text btn-rounded btn-sm" data-toggle="modal" data-target="#add-Ouput">
                            <i class="ti-plus btn-icon-prepend"></i>Add Output
                        </button>
                    </a>
                </div>
                <div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <p class="card-title text-md-center text-xl-left">Output</p>
                    <div class=" flex-wrap justify-content-between justify-content-md-center justify-content-xl-between align-items-center">
                        <table id="example1" class="table table-hover">
                            <thead style="font-size:10px">
                                <tr>
                                    <th>OutPut ID</th>
                                    <th>ProductName</th>
                                    <th>Customer</th>
                                    <th>Quantity</th>
                                    <th>Status</th>
                                    <th>Date Recorded</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    @foreach (var item in myList)
                                    {
                                        <td>@item.Id</td>
                                        <td></td>
                                        <td></td>
                                        <td>@item.Count</td>
                                        <td>@item.Status</td>
                                        <td></td>
                                        <td>
                                            <a href="#" data-toggle="tooltip" title="Edit">
                                                <button type="button" class="btn btn-primary btn-sm btn-rounded" data-toggle="modal" data-target="#edit-Output"><i class="ti-pencil-alt btn-icon-prepend"></i></button>
                                            </a>
                                        </td>
                                    }

                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="modal fade" id="edit-Output">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Edit Sales</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" asp-action="editOutput" asp-controller="Output">
                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <label for="Item">Product</label>

                                    <select class="form-control" name="productId">
                                        @foreach (var item in ViewBag.SelectListProduct)
                                        {
                                            <option value="@item.Value">@item.Text</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group col-md-12">
                                    <label for="Item">Customer</label>

                                    <select class="form-control" name="CustomerId">
                                        @foreach (var item in ViewBag.SelectListCustomer)
                                        {
                                            <option value="@item.Value">@item.Text</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group col-md-12">
                                    <label for="Sale Quantity">Quantity</label>
                                    <input type="number" class="form-control" name="Quantity" placeholder="Sale Quantity">
                                </div>

                            </div>
                            <button type="submit" class="btn btn-primary btn-rounded">Save</button>
                            <button type="button" class="btn btn-default btn-rounded" data-dismiss="modal">Cancel</button>
                        </div>
                        <!-- /.card-body -->

                    </form>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <div class="modal fade" id="add-Ouput">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Add Sales</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" asp-action="addOutput" asp-controller="Output">
                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-12">
                                    <label for="Item">Product</label>
                                    <select class="form-control" name="productId">
                                        @foreach (var item in ViewBag.SelectListProduct)
                                        {
                                            <option value="@item.Value">@item.Text</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group col-md-12">
                                    <label for="Item">Customer</label>
                                    <select class="form-control" name="customerId">
                                        @foreach (var item in ViewBag.SelectListCustomer)
                                        {
                                            <option value="@item.Value">@item.Text</option>
                                        }
                                    </select>
                                </div>
                                <div class="form-group col-md-12">
                                    <label for="Sale Quantity">Quantity</label>
                                    <input type="number" class="form-control" name="Quantity" placeholder="Sale Quantity">
                                </div>

                            </div>
                            <button type="submit" class="btn btn-primary btn-rounded">Save</button>
                            <button type="button" class="btn btn-default btn-rounded" data-dismiss="modal">Cancel</button>
                        </div>
                        <!-- /.card-body -->

                    </form>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>